version: "3.5"
name: inbox-zero-services
services:
  db:
    image: postgres
    restart: always
    container_name: inbox-zero
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "inboxzero"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 8009:5432

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - database-data:/data
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: "27191372ba5c50fd95f59baa43d0e3d2"
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.

volumes:
  database-data:
